# Generated by Django 3.2.25 on 2024-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalfApp', '0002_auto_20240721_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(4, '四级'), (2, '二级'), (1, '一级'), (3, '三级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(2, '未使用'), (1, '已占有')], default=2, verbose_name='状态')),
            ],
        ),
    ]
