# Generated by Django 3.2.25 on 2024-08-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalfApp', '0005_auto_20240815_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '四级'), (2, '二级'), (1, '一级'), (3, '三级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '未使用'), (1, '已占有')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
    ]
