# Generated by Django 3.2.25 on 2024-08-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalfApp', '0006_auto_20240816_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '三级'), (4, '四级'), (1, '一级'), (2, '二级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占有'), (2, '未使用')], default=2, verbose_name='状态'),
        ),
    ]
