# Generated by Django 3.2.25 on 2024-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalfApp', '0009_auto_20240827_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('count', models.IntegerField(default=0, verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '三级'), (2, '二级'), (1, '一级'), (4, '四级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占有'), (2, '未使用')], default=2, verbose_name='状态'),
        ),
    ]
